/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILanguageTranslationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Translate German to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        LanguageTranslationResponse LanguageTranslationTranslateDeuToEng (LanguageTranslationRequest input);

        /// <summary>
        /// Translate German to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        ApiResponse<LanguageTranslationResponse> LanguageTranslationTranslateDeuToEngWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate English to German text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        LanguageTranslationResponse LanguageTranslationTranslateEngToDeu (LanguageTranslationRequest input);

        /// <summary>
        /// Translate English to German text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        ApiResponse<LanguageTranslationResponse> LanguageTranslationTranslateEngToDeuWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate English to Russian text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        LanguageTranslationResponse LanguageTranslationTranslateEngToRus (LanguageTranslationRequest input);

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        ApiResponse<LanguageTranslationResponse> LanguageTranslationTranslateEngToRusWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate Russian to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        LanguageTranslationResponse LanguageTranslationTranslateRusToEng (LanguageTranslationRequest input);

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        ApiResponse<LanguageTranslationResponse> LanguageTranslationTranslateRusToEngWithHttpInfo (LanguageTranslationRequest input);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Translate German to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateDeuToEngAsync (LanguageTranslationRequest input);

        /// <summary>
        /// Translate German to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateDeuToEngAsyncWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate English to German text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateEngToDeuAsync (LanguageTranslationRequest input);

        /// <summary>
        /// Translate English to German text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateEngToDeuAsyncWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate English to Russian text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateEngToRusAsync (LanguageTranslationRequest input);

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateEngToRusAsyncWithHttpInfo (LanguageTranslationRequest input);
        /// <summary>
        /// Translate Russian to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateRusToEngAsync (LanguageTranslationRequest input);

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI
        /// </summary>
        /// <remarks>
        /// Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateRusToEngAsyncWithHttpInfo (LanguageTranslationRequest input);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LanguageTranslationApi : ILanguageTranslationApi
    {
        private Cloudmersive.APIClient.NET.NLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageTranslationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LanguageTranslationApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NET.NLP.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NET.NLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageTranslationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LanguageTranslationApi(Cloudmersive.APIClient.NET.NLP.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NET.NLP.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NET.NLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.NLP.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.NLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Translate German to English text with Deep Learning AI Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        public LanguageTranslationResponse LanguageTranslationTranslateDeuToEng (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = LanguageTranslationTranslateDeuToEngWithHttpInfo(input);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Translate German to English text with Deep Learning AI Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        public ApiResponse< LanguageTranslationResponse > LanguageTranslationTranslateDeuToEngWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateDeuToEng");

            var localVarPath = "/nlp-v2/translate/language/deu/to/eng";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateDeuToEng", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate German to English text with Deep Learning AI Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        public async System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateDeuToEngAsync (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = await LanguageTranslationTranslateDeuToEngAsyncWithHttpInfo(input);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Translate German to English text with Deep Learning AI Automatically translates input text in German to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateDeuToEngAsyncWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateDeuToEng");

            var localVarPath = "/nlp-v2/translate/language/deu/to/eng";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateDeuToEng", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate English to German text with Deep Learning AI Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        public LanguageTranslationResponse LanguageTranslationTranslateEngToDeu (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = LanguageTranslationTranslateEngToDeuWithHttpInfo(input);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Translate English to German text with Deep Learning AI Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        public ApiResponse< LanguageTranslationResponse > LanguageTranslationTranslateEngToDeuWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateEngToDeu");

            var localVarPath = "/nlp-v2/translate/language/eng/to/deu";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateEngToDeu", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate English to German text with Deep Learning AI Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        public async System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateEngToDeuAsync (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = await LanguageTranslationTranslateEngToDeuAsyncWithHttpInfo(input);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Translate English to German text with Deep Learning AI Automatically translates input text in English to output text in German using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateEngToDeuAsyncWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateEngToDeu");

            var localVarPath = "/nlp-v2/translate/language/eng/to/deu";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateEngToDeu", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        public LanguageTranslationResponse LanguageTranslationTranslateEngToRus (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = LanguageTranslationTranslateEngToRusWithHttpInfo(input);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        public ApiResponse< LanguageTranslationResponse > LanguageTranslationTranslateEngToRusWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateEngToRus");

            var localVarPath = "/nlp-v2/translate/language/eng/to/rus";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateEngToRus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        public async System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateEngToRusAsync (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = await LanguageTranslationTranslateEngToRusAsyncWithHttpInfo(input);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Translate English to Russian text with Deep Learning AI Automatically translates input text in English to output text in Russian using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateEngToRusAsyncWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateEngToRus");

            var localVarPath = "/nlp-v2/translate/language/eng/to/rus";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateEngToRus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>LanguageTranslationResponse</returns>
        public LanguageTranslationResponse LanguageTranslationTranslateRusToEng (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = LanguageTranslationTranslateRusToEngWithHttpInfo(input);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>ApiResponse of LanguageTranslationResponse</returns>
        public ApiResponse< LanguageTranslationResponse > LanguageTranslationTranslateRusToEngWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateRusToEng");

            var localVarPath = "/nlp-v2/translate/language/rus/to/eng";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateRusToEng", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of LanguageTranslationResponse</returns>
        public async System.Threading.Tasks.Task<LanguageTranslationResponse> LanguageTranslationTranslateRusToEngAsync (LanguageTranslationRequest input)
        {
             ApiResponse<LanguageTranslationResponse> localVarResponse = await LanguageTranslationTranslateRusToEngAsyncWithHttpInfo(input);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Translate Russian to English text with Deep Learning AI Automatically translates input text in Russian to output text in English using advanced Deep Learning and Neural NLP.  Consumes 1-2 API calls per input sentence.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="input">Input translation request</param>
        /// <returns>Task of ApiResponse (LanguageTranslationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LanguageTranslationResponse>> LanguageTranslationTranslateRusToEngAsyncWithHttpInfo (LanguageTranslationRequest input)
        {
            // verify the required parameter 'input' is set
            if (input == null)
                throw new ApiException(400, "Missing required parameter 'input' when calling LanguageTranslationApi->LanguageTranslationTranslateRusToEng");

            var localVarPath = "/nlp-v2/translate/language/rus/to/eng";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (input != null && input.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(input); // http body (model) parameter
            }
            else
            {
                localVarPostBody = input; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageTranslationTranslateRusToEng", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LanguageTranslationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LanguageTranslationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(LanguageTranslationResponse)));
        }

    }
}
