/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPosTaggerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagAdjectives (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagAdjectivesWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagAdverbs (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagAdverbsWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to nouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagNouns (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagNounsWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagPronouns (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagPronounsWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagSentence (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagSentenceWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to verbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        PosResponse PosTaggerTagVerbs (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        ApiResponse<PosResponse> PosTaggerTagVerbsWithHttpInfo (PosRequest request);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagAdjectivesAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagAdjectivesAsyncWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagAdverbsAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagAdverbsAsyncWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to nouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagNounsAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagNounsAsyncWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagPronounsAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagPronounsAsyncWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagSentenceAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagSentenceAsyncWithHttpInfo (PosRequest request);
        /// <summary>
        /// Part-of-speech tag a string, filter to verbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        System.Threading.Tasks.Task<PosResponse> PosTaggerTagVerbsAsync (PosRequest request);

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs
        /// </summary>
        /// <remarks>
        /// Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagVerbsAsyncWithHttpInfo (PosRequest request);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PosTaggerApi : IPosTaggerApi
    {
        private Cloudmersive.APIClient.NET.NLP.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PosTaggerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PosTaggerApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NET.NLP.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NET.NLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PosTaggerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PosTaggerApi(Cloudmersive.APIClient.NET.NLP.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NET.NLP.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NET.NLP.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.NLP.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.NLP.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagAdjectives (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagAdjectivesWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagAdjectivesWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagAdjectives");

            var localVarPath = "/nlp-v2/pos/tag/adjectives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagAdjectives", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagAdjectivesAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagAdjectivesAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adjectives Part-of-speech (POS) tag a string, find the adjectives, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagAdjectivesAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagAdjectives");

            var localVarPath = "/nlp-v2/pos/tag/adjectives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagAdjectives", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagAdverbs (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagAdverbsWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagAdverbsWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagAdverbs");

            var localVarPath = "/nlp-v2/pos/tag/adverbs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagAdverbs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagAdverbsAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagAdverbsAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string, filter to adverbs Part-of-speech (POS) tag a string, find the adverbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagAdverbsAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagAdverbs");

            var localVarPath = "/nlp-v2/pos/tag/adverbs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagAdverbs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagNouns (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagNounsWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagNounsWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagNouns");

            var localVarPath = "/nlp-v2/pos/tag/nouns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagNouns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagNounsAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagNounsAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string, filter to nouns Part-of-speech (POS) tag a string, find the nouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagNounsAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagNouns");

            var localVarPath = "/nlp-v2/pos/tag/nouns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagNouns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagPronouns (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagPronounsWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagPronounsWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagPronouns");

            var localVarPath = "/nlp-v2/pos/tag/pronouns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagPronouns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagPronounsAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagPronounsAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string, filter to pronouns Part-of-speech (POS) tag a string, find the pronouns, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagPronounsAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagPronouns");

            var localVarPath = "/nlp-v2/pos/tag/pronouns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagPronouns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string Part-of-speech (POS) tag a string and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagSentence (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagSentenceWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string Part-of-speech (POS) tag a string and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagSentenceWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagSentence");

            var localVarPath = "/nlp-v2/pos/tag/sentence";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagSentence", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string Part-of-speech (POS) tag a string and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagSentenceAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagSentenceAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string Part-of-speech (POS) tag a string and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagSentenceAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagSentence");

            var localVarPath = "/nlp-v2/pos/tag/sentence";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagSentence", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>PosResponse</returns>
        public PosResponse PosTaggerTagVerbs (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = PosTaggerTagVerbsWithHttpInfo(request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>ApiResponse of PosResponse</returns>
        public ApiResponse< PosResponse > PosTaggerTagVerbsWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagVerbs");

            var localVarPath = "/nlp-v2/pos/tag/verbs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagVerbs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of PosResponse</returns>
        public async System.Threading.Tasks.Task<PosResponse> PosTaggerTagVerbsAsync (PosRequest request)
        {
             ApiResponse<PosResponse> localVarResponse = await PosTaggerTagVerbsAsyncWithHttpInfo(request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Part-of-speech tag a string, filter to verbs Part-of-speech (POS) tag a string, find the verbs, and return result as JSON
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.NLP.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="request">Input string</param>
        /// <returns>Task of ApiResponse (PosResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PosResponse>> PosTaggerTagVerbsAsyncWithHttpInfo (PosRequest request)
        {
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling PosTaggerApi->PosTaggerTagVerbs");

            var localVarPath = "/nlp-v2/pos/tag/verbs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PosTaggerTagVerbs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PosResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PosResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PosResponse)));
        }

    }
}
