/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.NLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.NLP.Model
{
    /// <summary>
    /// One rephrasing of an original input sentence
    /// </summary>
    [DataContract]
    public partial class RephrasedSentenceOption :  IEquatable<RephrasedSentenceOption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RephrasedSentenceOption" /> class.
        /// </summary>
        /// <param name="rephrasedOptionIndex">Ordered index of the rephrasing option, 1-based, with 1 being the best option.</param>
        /// <param name="rephrasedSentenceText">One sentence of output rephrased text of original input sentence.</param>
        public RephrasedSentenceOption(int? rephrasedOptionIndex = default(int?), string rephrasedSentenceText = default(string))
        {
            this.RephrasedOptionIndex = rephrasedOptionIndex;
            this.RephrasedSentenceText = rephrasedSentenceText;
        }
        
        /// <summary>
        /// Ordered index of the rephrasing option, 1-based, with 1 being the best option
        /// </summary>
        /// <value>Ordered index of the rephrasing option, 1-based, with 1 being the best option</value>
        [DataMember(Name="RephrasedOptionIndex", EmitDefaultValue=false)]
        public int? RephrasedOptionIndex { get; set; }

        /// <summary>
        /// One sentence of output rephrased text of original input sentence
        /// </summary>
        /// <value>One sentence of output rephrased text of original input sentence</value>
        [DataMember(Name="RephrasedSentenceText", EmitDefaultValue=false)]
        public string RephrasedSentenceText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RephrasedSentenceOption {\n");
            sb.Append("  RephrasedOptionIndex: ").Append(RephrasedOptionIndex).Append("\n");
            sb.Append("  RephrasedSentenceText: ").Append(RephrasedSentenceText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RephrasedSentenceOption);
        }

        /// <summary>
        /// Returns true if RephrasedSentenceOption instances are equal
        /// </summary>
        /// <param name="input">Instance of RephrasedSentenceOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RephrasedSentenceOption input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RephrasedOptionIndex == input.RephrasedOptionIndex ||
                    (this.RephrasedOptionIndex != null &&
                    this.RephrasedOptionIndex.Equals(input.RephrasedOptionIndex))
                ) && 
                (
                    this.RephrasedSentenceText == input.RephrasedSentenceText ||
                    (this.RephrasedSentenceText != null &&
                    this.RephrasedSentenceText.Equals(input.RephrasedSentenceText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RephrasedOptionIndex != null)
                    hashCode = hashCode * 59 + this.RephrasedOptionIndex.GetHashCode();
                if (this.RephrasedSentenceText != null)
                    hashCode = hashCode * 59 + this.RephrasedSentenceText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
