/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.NLP.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.NLP.Model
{
    /// <summary>
    /// One input sentence and associated rephrasing results
    /// </summary>
    [DataContract]
    public partial class RephrasedSentence :  IEquatable<RephrasedSentence>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RephrasedSentence" /> class.
        /// </summary>
        /// <param name="sentenceIndex">Index of the sentence, 1-based, ordered.</param>
        /// <param name="originalSentenceText">Original input sentence text.</param>
        /// <param name="rephrasings">Rephrasing text options, candidates of the original input sentence, in order - with best candidate first.</param>
        public RephrasedSentence(int? sentenceIndex = default(int?), string originalSentenceText = default(string), List<RephrasedSentenceOption> rephrasings = default(List<RephrasedSentenceOption>))
        {
            this.SentenceIndex = sentenceIndex;
            this.OriginalSentenceText = originalSentenceText;
            this.Rephrasings = rephrasings;
        }
        
        /// <summary>
        /// Index of the sentence, 1-based, ordered
        /// </summary>
        /// <value>Index of the sentence, 1-based, ordered</value>
        [DataMember(Name="SentenceIndex", EmitDefaultValue=false)]
        public int? SentenceIndex { get; set; }

        /// <summary>
        /// Original input sentence text
        /// </summary>
        /// <value>Original input sentence text</value>
        [DataMember(Name="OriginalSentenceText", EmitDefaultValue=false)]
        public string OriginalSentenceText { get; set; }

        /// <summary>
        /// Rephrasing text options, candidates of the original input sentence, in order - with best candidate first
        /// </summary>
        /// <value>Rephrasing text options, candidates of the original input sentence, in order - with best candidate first</value>
        [DataMember(Name="Rephrasings", EmitDefaultValue=false)]
        public List<RephrasedSentenceOption> Rephrasings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RephrasedSentence {\n");
            sb.Append("  SentenceIndex: ").Append(SentenceIndex).Append("\n");
            sb.Append("  OriginalSentenceText: ").Append(OriginalSentenceText).Append("\n");
            sb.Append("  Rephrasings: ").Append(Rephrasings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RephrasedSentence);
        }

        /// <summary>
        /// Returns true if RephrasedSentence instances are equal
        /// </summary>
        /// <param name="input">Instance of RephrasedSentence to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RephrasedSentence input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SentenceIndex == input.SentenceIndex ||
                    (this.SentenceIndex != null &&
                    this.SentenceIndex.Equals(input.SentenceIndex))
                ) && 
                (
                    this.OriginalSentenceText == input.OriginalSentenceText ||
                    (this.OriginalSentenceText != null &&
                    this.OriginalSentenceText.Equals(input.OriginalSentenceText))
                ) && 
                (
                    this.Rephrasings == input.Rephrasings ||
                    this.Rephrasings != null &&
                    this.Rephrasings.SequenceEqual(input.Rephrasings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SentenceIndex != null)
                    hashCode = hashCode * 59 + this.SentenceIndex.GetHashCode();
                if (this.OriginalSentenceText != null)
                    hashCode = hashCode * 59 + this.OriginalSentenceText.GetHashCode();
                if (this.Rephrasings != null)
                    hashCode = hashCode * 59 + this.Rephrasings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
