/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing LanguageTranslationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LanguageTranslationApiTests
    {
        private LanguageTranslationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LanguageTranslationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LanguageTranslationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LanguageTranslationApi
            //Assert.IsInstanceOfType(typeof(LanguageTranslationApi), instance, "instance is a LanguageTranslationApi");
        }

        
        /// <summary>
        /// Test LanguageTranslationTranslateDeuToEng
        /// </summary>
        [Test]
        public void LanguageTranslationTranslateDeuToEngTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LanguageTranslationRequest input = null;
            //var response = instance.LanguageTranslationTranslateDeuToEng(input);
            //Assert.IsInstanceOf<LanguageTranslationResponse> (response, "response is LanguageTranslationResponse");
        }
        
        /// <summary>
        /// Test LanguageTranslationTranslateEngToDeu
        /// </summary>
        [Test]
        public void LanguageTranslationTranslateEngToDeuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LanguageTranslationRequest input = null;
            //var response = instance.LanguageTranslationTranslateEngToDeu(input);
            //Assert.IsInstanceOf<LanguageTranslationResponse> (response, "response is LanguageTranslationResponse");
        }
        
        /// <summary>
        /// Test LanguageTranslationTranslateEngToRus
        /// </summary>
        [Test]
        public void LanguageTranslationTranslateEngToRusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LanguageTranslationRequest input = null;
            //var response = instance.LanguageTranslationTranslateEngToRus(input);
            //Assert.IsInstanceOf<LanguageTranslationResponse> (response, "response is LanguageTranslationResponse");
        }
        
        /// <summary>
        /// Test LanguageTranslationTranslateRusToEng
        /// </summary>
        [Test]
        public void LanguageTranslationTranslateRusToEngTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LanguageTranslationRequest input = null;
            //var response = instance.LanguageTranslationTranslateRusToEng(input);
            //Assert.IsInstanceOf<LanguageTranslationResponse> (response, "response is LanguageTranslationResponse");
        }
        
    }

}
