/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing PosTaggerJsonApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PosTaggerJsonApiTests
    {
        private PosTaggerJsonApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PosTaggerJsonApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PosTaggerJsonApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PosTaggerJsonApi
            //Assert.IsInstanceOfType(typeof(PosTaggerJsonApi), instance, "instance is a PosTaggerJsonApi");
        }

        
        /// <summary>
        /// Test PosTaggerJsonPost
        /// </summary>
        [Test]
        public void PosTaggerJsonPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PosRequest request = null;
            //var response = instance.PosTaggerJsonPost(request);
            //Assert.IsInstanceOf<PosResponse> (response, "response is PosResponse");
        }
        
    }

}
