/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing SpellCheckApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpellCheckApiTests
    {
        private SpellCheckApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpellCheckApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpellCheckApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpellCheckApi
            //Assert.IsInstanceOfType(typeof(SpellCheckApi), instance, "instance is a SpellCheckApi");
        }

        
        /// <summary>
        /// Test SpellCheckCheckJson
        /// </summary>
        [Test]
        public void SpellCheckCheckJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckCheckJson(value);
            //Assert.IsInstanceOf<CheckJsonResponse> (response, "response is CheckJsonResponse");
        }
        
        /// <summary>
        /// Test SpellCheckCheckSentenceJson
        /// </summary>
        [Test]
        public void SpellCheckCheckSentenceJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckCheckSentenceJson(value);
            //Assert.IsInstanceOf<CheckSentenceJsonResponse> (response, "response is CheckSentenceJsonResponse");
        }
        
        /// <summary>
        /// Test SpellCheckCheckSentenceString
        /// </summary>
        [Test]
        public void SpellCheckCheckSentenceStringTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckCheckSentenceString(value);
            //Assert.IsInstanceOf<bool?> (response, "response is bool?");
        }
        
        /// <summary>
        /// Test SpellCheckCorrect
        /// </summary>
        [Test]
        public void SpellCheckCorrectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckCorrect(value);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SpellCheckCorrectJson
        /// </summary>
        [Test]
        public void SpellCheckCorrectJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckCorrectJson(value);
            //Assert.IsInstanceOf<CorrectJsonResponse> (response, "response is CorrectJsonResponse");
        }
        
        /// <summary>
        /// Test SpellCheckPost
        /// </summary>
        [Test]
        public void SpellCheckPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.SpellCheckPost(value);
            //Assert.IsInstanceOf<bool?> (response, "response is bool?");
        }
        
    }

}
