/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing SpellcheckApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpellcheckApiTests
    {
        private SpellcheckApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpellcheckApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpellcheckApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpellcheckApi
            //Assert.IsInstanceOfType(typeof(SpellcheckApi), instance, "instance is a SpellcheckApi");
        }

        
        /// <summary>
        /// Test SpellcheckCheckSentence
        /// </summary>
        [Test]
        public void SpellcheckCheckSentenceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CheckSentenceRequest value = null;
            //var response = instance.SpellcheckCheckSentence(value);
            //Assert.IsInstanceOf<CheckSentenceResponse> (response, "response is CheckSentenceResponse");
        }
        
        /// <summary>
        /// Test SpellcheckCorrectJson
        /// </summary>
        [Test]
        public void SpellcheckCorrectJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CheckWordRequest value = null;
            //var response = instance.SpellcheckCorrectJson(value);
            //Assert.IsInstanceOf<CheckWordResponse> (response, "response is CheckWordResponse");
        }
        
    }

}
