/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.NLP.Client;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing WordsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WordsApiTests
    {
        private WordsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WordsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WordsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WordsApi
            //Assert.IsInstanceOfType(typeof(WordsApi), instance, "instance is a WordsApi");
        }

        
        /// <summary>
        /// Test WordsAdjectives
        /// </summary>
        [Test]
        public void WordsAdjectivesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsAdjectives(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsAdverbs
        /// </summary>
        [Test]
        public void WordsAdverbsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsAdverbs(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsGetWordsJson
        /// </summary>
        [Test]
        public void WordsGetWordsJsonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsGetWordsJson(input);
            //Assert.IsInstanceOf<GetWordsJsonResponse> (response, "response is GetWordsJsonResponse");
        }
        
        /// <summary>
        /// Test WordsGetWordsString
        /// </summary>
        [Test]
        public void WordsGetWordsStringTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsGetWordsString(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsNouns
        /// </summary>
        [Test]
        public void WordsNounsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsNouns(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsPost
        /// </summary>
        [Test]
        public void WordsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsPost(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsPronouns
        /// </summary>
        [Test]
        public void WordsPronounsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsPronouns(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test WordsProperNouns
        /// </summary>
        [Test]
        public void WordsProperNounsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string input = null;
            //var response = instance.WordsProperNouns(input);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
