/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing CorrectJsonResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CorrectJsonResponseTests
    {
        // TODO uncomment below to declare an instance variable for CorrectJsonResponse
        //private CorrectJsonResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CorrectJsonResponse
            //instance = new CorrectJsonResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CorrectJsonResponse
        /// </summary>
        [Test]
        public void CorrectJsonResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CorrectJsonResponse
            //Assert.IsInstanceOfType<CorrectJsonResponse> (instance, "variable 'instance' is a CorrectJsonResponse");
        }


        /// <summary>
        /// Test the property 'Correct'
        /// </summary>
        [Test]
        public void CorrectTest()
        {
            // TODO unit test for the property 'Correct'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Test]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }

    }

}
