/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing ExtractEntitiesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtractEntitiesRequestTests
    {
        // TODO uncomment below to declare an instance variable for ExtractEntitiesRequest
        //private ExtractEntitiesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtractEntitiesRequest
            //instance = new ExtractEntitiesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractEntitiesRequest
        /// </summary>
        [Test]
        public void ExtractEntitiesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtractEntitiesRequest
            //Assert.IsInstanceOfType<ExtractEntitiesRequest> (instance, "variable 'instance' is a ExtractEntitiesRequest");
        }


        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Test]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

    }

}
