/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing HateSpeechAnalysisRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HateSpeechAnalysisRequestTests
    {
        // TODO uncomment below to declare an instance variable for HateSpeechAnalysisRequest
        //private HateSpeechAnalysisRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HateSpeechAnalysisRequest
            //instance = new HateSpeechAnalysisRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HateSpeechAnalysisRequest
        /// </summary>
        [Test]
        public void HateSpeechAnalysisRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HateSpeechAnalysisRequest
            //Assert.IsInstanceOfType<HateSpeechAnalysisRequest> (instance, "variable 'instance' is a HateSpeechAnalysisRequest");
        }


        /// <summary>
        /// Test the property 'TextToAnalyze'
        /// </summary>
        [Test]
        public void TextToAnalyzeTest()
        {
            // TODO unit test for the property 'TextToAnalyze'
        }

    }

}
