/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing LanguageTranslationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LanguageTranslationResponseTests
    {
        // TODO uncomment below to declare an instance variable for LanguageTranslationResponse
        //private LanguageTranslationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LanguageTranslationResponse
            //instance = new LanguageTranslationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LanguageTranslationResponse
        /// </summary>
        [Test]
        public void LanguageTranslationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LanguageTranslationResponse
            //Assert.IsInstanceOfType<LanguageTranslationResponse> (instance, "variable 'instance' is a LanguageTranslationResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'TranslatedTextResult'
        /// </summary>
        [Test]
        public void TranslatedTextResultTest()
        {
            // TODO unit test for the property 'TranslatedTextResult'
        }
        /// <summary>
        /// Test the property 'SentenceCount'
        /// </summary>
        [Test]
        public void SentenceCountTest()
        {
            // TODO unit test for the property 'SentenceCount'
        }

    }

}
