/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing PosSentence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PosSentenceTests
    {
        // TODO uncomment below to declare an instance variable for PosSentence
        //private PosSentence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PosSentence
            //instance = new PosSentence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PosSentence
        /// </summary>
        [Test]
        public void PosSentenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PosSentence
            //Assert.IsInstanceOfType<PosSentence> (instance, "variable 'instance' is a PosSentence");
        }


        /// <summary>
        /// Test the property 'Words'
        /// </summary>
        [Test]
        public void WordsTest()
        {
            // TODO unit test for the property 'Words'
        }

    }

}
