/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing RephraseRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RephraseRequestTests
    {
        // TODO uncomment below to declare an instance variable for RephraseRequest
        //private RephraseRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RephraseRequest
            //instance = new RephraseRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RephraseRequest
        /// </summary>
        [Test]
        public void RephraseRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RephraseRequest
            //Assert.IsInstanceOfType<RephraseRequest> (instance, "variable 'instance' is a RephraseRequest");
        }


        /// <summary>
        /// Test the property 'TextToTranslate'
        /// </summary>
        [Test]
        public void TextToTranslateTest()
        {
            // TODO unit test for the property 'TextToTranslate'
        }
        /// <summary>
        /// Test the property 'TargetRephrasingCount'
        /// </summary>
        [Test]
        public void TargetRephrasingCountTest()
        {
            // TODO unit test for the property 'TargetRephrasingCount'
        }

    }

}
