/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing RephrasedSentenceOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RephrasedSentenceOptionTests
    {
        // TODO uncomment below to declare an instance variable for RephrasedSentenceOption
        //private RephrasedSentenceOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RephrasedSentenceOption
            //instance = new RephrasedSentenceOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RephrasedSentenceOption
        /// </summary>
        [Test]
        public void RephrasedSentenceOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RephrasedSentenceOption
            //Assert.IsInstanceOfType<RephrasedSentenceOption> (instance, "variable 'instance' is a RephrasedSentenceOption");
        }


        /// <summary>
        /// Test the property 'RephrasedOptionIndex'
        /// </summary>
        [Test]
        public void RephrasedOptionIndexTest()
        {
            // TODO unit test for the property 'RephrasedOptionIndex'
        }
        /// <summary>
        /// Test the property 'RephrasedSentenceText'
        /// </summary>
        [Test]
        public void RephrasedSentenceTextTest()
        {
            // TODO unit test for the property 'RephrasedSentenceText'
        }

    }

}
