/* 
 * nlpapiv2
 *
 * The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing SimilarityAnalysisRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SimilarityAnalysisRequestTests
    {
        // TODO uncomment below to declare an instance variable for SimilarityAnalysisRequest
        //private SimilarityAnalysisRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimilarityAnalysisRequest
            //instance = new SimilarityAnalysisRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimilarityAnalysisRequest
        /// </summary>
        [Test]
        public void SimilarityAnalysisRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SimilarityAnalysisRequest
            //Assert.IsInstanceOfType<SimilarityAnalysisRequest> (instance, "variable 'instance' is a SimilarityAnalysisRequest");
        }


        /// <summary>
        /// Test the property 'TextToAnalyze1'
        /// </summary>
        [Test]
        public void TextToAnalyze1Test()
        {
            // TODO unit test for the property 'TextToAnalyze1'
        }
        /// <summary>
        /// Test the property 'TextToAnalyze2'
        /// </summary>
        [Test]
        public void TextToAnalyze2Test()
        {
            // TODO unit test for the property 'TextToAnalyze2'
        }

    }

}
