/* 
 * nlpapi
 *
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.NLP.Api;
using Cloudmersive.APIClient.NET.NLP.Model;
using Cloudmersive.APIClient.NET.NLP.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.NLP.Test
{
    /// <summary>
    ///  Class for testing WordPosition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WordPositionTests
    {
        // TODO uncomment below to declare an instance variable for WordPosition
        //private WordPosition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WordPosition
            //instance = new WordPosition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WordPosition
        /// </summary>
        [Test]
        public void WordPositionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WordPosition
            //Assert.IsInstanceOfType<WordPosition> (instance, "variable 'instance' is a WordPosition");
        }


        /// <summary>
        /// Test the property 'Word'
        /// </summary>
        [Test]
        public void WordTest()
        {
            // TODO unit test for the property 'Word'
        }
        /// <summary>
        /// Test the property 'WordIndex'
        /// </summary>
        [Test]
        public void WordIndexTest()
        {
            // TODO unit test for the property 'WordIndex'
        }
        /// <summary>
        /// Test the property 'StartPosition'
        /// </summary>
        [Test]
        public void StartPositionTest()
        {
            // TODO unit test for the property 'StartPosition'
        }
        /// <summary>
        /// Test the property 'EndPosition'
        /// </summary>
        [Test]
        public void EndPositionTest()
        {
            // TODO unit test for the property 'EndPosition'
        }

    }

}
